development:
    adapter: postgresql
    encoding: unicode
    database: database_postgresql
    pool: 5
    username: postgres
    password: secret

test:
   adapter: postgresql
    encoding: unicode
    database: database_postgresql_test
    pool: 5
    username: postgres
    password: secret

production:
   adapter: postgresql
    encoding: unicode
    database: database_postgresql
    pool: 5
    username: postgres
    password: secret